"""updated cascade

Revision ID: 1fcce626be31
Revises: a68be42be990
Create Date: 2025-07-29 19:29:45.704927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcce626be31'
down_revision: Union[str, Sequence[str], None] = 'a68be42be990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('friendrequest_to_user_id_fkey'), 'friendrequest', type_='foreignkey')
    op.drop_constraint(op.f('friendrequest_from_user_id_fkey'), 'friendrequest', type_='foreignkey')
    op.create_foreign_key(None, 'friendrequest', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friendrequest', 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'friendrequest', type_='foreignkey')
    op.drop_constraint(None, 'friendrequest', type_='foreignkey')
    op.create_foreign_key(op.f('friendrequest_from_user_id_fkey'), 'friendrequest', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key(op.f('friendrequest_to_user_id_fkey'), 'friendrequest', 'users', ['to_user_id'], ['id'])
    # ### end Alembic commands ###
