"""added cascade delete 

Revision ID: 22078ef01948
Revises: 644e82cb5814
Create Date: 2025-08-26 16:32:46.158443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22078ef01948'
down_revision: Union[str, Sequence[str], None] = '644e82cb5814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chatmembers_chat_id_fkey'), 'chatmembers', type_='foreignkey')
    op.create_foreign_key(None, 'chatmembers', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatmembers', type_='foreignkey')
    op.create_foreign_key(op.f('chatmembers_chat_id_fkey'), 'chatmembers', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
