"""added is_revoked to refresh token table

Revision ID: 2df237a36dd1
Revises: 6280a603ed24
Create Date: 2025-12-25 18:46:14.025232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df237a36dd1'
down_revision: Union[str, Sequence[str], None] = '6280a603ed24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chatmembers', ['id'])
    op.create_unique_constraint(None, 'chats', ['id'])
    op.create_unique_constraint(None, 'friendrequest', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    op.add_column('refreshtoken', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'refreshtoken', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refreshtoken', type_='unique')
    op.drop_column('refreshtoken', 'is_revoked')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'friendrequest', type_='unique')
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_constraint(None, 'chatmembers', type_='unique')
    # ### end Alembic commands ###
