"""added file type and name

Revision ID: 5f24f0a6ccb7
Revises: 7d7e0621e7a3
Create Date: 2025-08-23 15:40:10.153721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f24f0a6ccb7'
down_revision: Union[str, Sequence[str], None] = '7d7e0621e7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_url', sa.String(), nullable=True))
    op.drop_column('messages', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'file_url')
    op.drop_column('messages', 'file_name')
    # ### end Alembic commands ###
