"""added reply

Revision ID: 644e82cb5814
Revises: 10c282161fba
Create Date: 2025-08-25 15:37:47.796981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644e82cb5814'
down_revision: Union[str, Sequence[str], None] = '10c282161fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to')
    # ### end Alembic commands ###
