"""added file type

Revision ID: 7d7e0621e7a3
Revises: c8df2b421019
Create Date: 2025-08-23 14:32:58.103791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7e0621e7a3'
down_revision: Union[str, Sequence[str], None] = 'c8df2b421019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_type')
    op.drop_column('messages', 'file')
    # ### end Alembic commands ###
