"""added file type and name with unque

Revision ID: a6211962fb8d
Revises: 5f24f0a6ccb7
Create Date: 2025-08-23 19:17:48.314088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6211962fb8d'
down_revision: Union[str, Sequence[str], None] = '5f24f0a6ccb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('unique_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'unique_name')
    # ### end Alembic commands ###
