"""updated cascade

Revision ID: a68be42be990
Revises: 297d67fce436
Create Date: 2025-07-29 19:27:42.292833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68be42be990'
down_revision: Union[str, Sequence[str], None] = '297d67fce436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chatmembers', ['id'])
    op.drop_constraint(op.f('chatmembers_user_id_fkey'), 'chatmembers', type_='foreignkey')
    op.create_foreign_key(None, 'chatmembers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'chats', ['id'])
    op.create_unique_constraint(None, 'friendrequest', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'friendrequest', type_='unique')
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_constraint(None, 'chatmembers', type_='foreignkey')
    op.create_foreign_key(op.f('chatmembers_user_id_fkey'), 'chatmembers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chatmembers', type_='unique')
    # ### end Alembic commands ###
