"""updated currency typo

Revision ID: b437404fff36
Revises: fbf5c734b351
Create Date: 2025-08-28 22:22:43.825598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b437404fff36'
down_revision: Union[str, Sequence[str], None] = 'fbf5c734b351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=False))
    op.drop_column('payments', 'curreny')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('curreny', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###
