"""added message status

Revision ID: c8df2b421019
Revises: a54675170e1c
Create Date: 2025-08-13 21:48:02.056388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8df2b421019'
down_revision: Union[str, Sequence[str], None] = 'a54675170e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE TYPE messagestatus AS ENUM ('sent', 'received', 'read');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.Enum(
        'sent', 'received', 'read', name='messagestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TYPE messagestatus;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
