"""added payment 1 table

Revision ID: fbf5c734b351
Revises: 0527fd1a29d6
Create Date: 2025-08-28 22:16:54.537660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf5c734b351'
down_revision: Union[str, Sequence[str], None] = '0527fd1a29d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['id'])
    op.add_column('users', sa.Column('is_pro', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pro_expiry', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_expiry')
    op.drop_column('users', 'is_pro')
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
